### ISSUE TITLE
Cardia wont find Zephyr HxM BT 

### ISSUE THREAD

**Issue by FLX3009** [uwburn/cardia#37] opened 2021-01-14 18:57 UTC
Hello there! 

I got an issue that my new Zephyr HxM BT (it's not the Smart model), won't be shown on any Serial Ports and can't connect at all.
Windows (10, newest updates installed) says that it's paired successfully. The device is turned on and should be fully functional. 

Tried to reset all Bluetooth configuration settings. Reinstalled BT drivers, changed the Serial Ports in Device manager but didn't helped either so I resetted that to default again. 

Wont connect via Bluetooth Smart HRP either. So I got the exact same screenshots as in #36. 

The logs are as following: 

2021-01-14 19:44:50,769 [1] INFO  MGT.Cardia.Program - Starting Cardia
2021-01-14 19:44:50,865 [1] DEBUG MGT.Cardia.BtHrpBundle - Retrieving heart rate capable devices
2021-01-14 19:44:50,911 [1] DEBUG MGT.Cardia.BtHrpBundle - Attempting to retrieve async result...
2021-01-14 19:44:51,024 [1] DEBUG MGT.Cardia.BtHrpBundle - Found 0 heart rate capable deices
2021-01-14 19:44:55,020 [1] DEBUG MGT.HRM.Zephyr_HxM.ZephyrHxM - Starting Zephyr HxM
2021-01-14 19:45:25,332 [6] DEBUG MGT.HRM.Zephyr_HxM.ZephyrHxM - Communication timeout elapsed
2021-01-14 19:45:25,332 [6] DEBUG MGT.HRM.Zephyr_HxM.ZephyrHxM - Stopping Zephyr HxM
2021-01-14 19:45:25,333 [6] DEBUG MGT.HRM.Zephyr_HxM.ZephyrHxM - Resetting counters
2021-01-14 19:47:48,423 [1] INFO  MGT.Cardia.Program - Starting Cardia
2021-01-14 19:47:48,506 [1] DEBUG MGT.Cardia.BtHrpBundle - Retrieving heart rate capable devices
2021-01-14 19:47:48,527 [1] DEBUG MGT.Cardia.BtHrpBundle - Attempting to retrieve async result...
2021-01-14 19:47:48,641 [1] DEBUG MGT.Cardia.BtHrpBundle - Found 0 heart rate capable deices
2021-01-14 19:47:52,954 [1] DEBUG MGT.HRM.Zephyr_HxM.ZephyrHxM - Starting Zephyr HxM
2021-01-14 19:48:01,864 [1] DEBUG MGT.HRM.Zephyr_HxM.ZephyrHxM - Stopping Zephyr HxM
2021-01-14 19:48:01,871 [1] DEBUG MGT.HRM.Zephyr_HxM.ZephyrHxM - Resetting counters
2021-01-14 19:48:06,369 [1] DEBUG MGT.HRM.Zephyr_HxM.ZephyrHxM - Starting Zephyr HxM
2021-01-14 19:48:36,715 [6] DEBUG MGT.HRM.Zephyr_HxM.ZephyrHxM - Communication timeout elapsed
2021-01-14 19:48:36,715 [6] DEBUG MGT.HRM.Zephyr_HxM.ZephyrHxM - Stopping Zephyr HxM
2021-01-14 19:48:36,716 [6] DEBUG MGT.HRM.Zephyr_HxM.ZephyrHxM - Resetting counters 

Anyone got any Idea what I could try else to get it right? 

Thanks in advance!

**Comment by mix3d** [comment] 2021-06-15 18:47
Dupe of #36?

**Comment by mix3d** [comment] 2021-06-15 18:48
Also related to #32

**Comment by uwburn** [comment] 2022-08-03 06:32
Stale.

**Closed as completed by uwburn** 2022-08-03 06:32 UTC
