### ISSUE TITLE
ANT+ just need integration

### ISSUE THREAD

**Issue by sur1v** [uwburn/cardia#48] opened 2023-01-31 00:38 UTC
Hello,

Thanks for this project, I really like it!

I just found this other project, also in C#, but that implements ANT+, looks like the job is done and we only need integration of the code.

https://github.com/julr/obs-ant-hrm

Thanks again!!!

**Comment by uwburn** [comment] 2023-02-02 07:59
Duplicate of #9

**Closed as completed by uwburn** 2023-02-02 07:59 UTC
Labels: duplicate

**Comment by sur1v** [comment] 2023-02-22 13:03
Sorry to comment on a closed issue, but this is not a duplicate IMHO. The cited is a feature request, this is code integration while they are similar and related is not the same job. Thanks!
