### ISSUE TITLE
Paired Polar HRM on correct W10 version won't connect

### ISSUE THREAD

**Issue by Kaszanas** [uwburn/cardia#15] opened 2018-03-17 22:27 UTC
Below is the Cardia log for that :(

[cardia_2018-03-17.log](https://github.com/uwburn/cardia/files/1822156/cardia_2018-03-17.log)

**Comment by uwburn** [comment] 2018-07-28 14:45
Duplicate of #3

**Closed as completed by uwburn** 2018-07-28 14:45 UTC
Labels: duplicate
