### ISSUE TITLE
graph timeline as option (in place of ecg simulation)

### ISSUE THREAD

**Issue by skonrad** [uwburn/cardia#40] opened 2021-05-22 01:51 UTC
Build something like this in the past and used a graph instead.

It might be more interesting to see the pulse behavior over time instead of just the current value (and min/max).

Remember when I streamed Alien Isolation and my pulse just rocketed up and ppl could see it for a minute (as that was the scale I set) how my pulse reacted to a specific scenario in the game.

_Might_ be able to add that option and create a pull request once I got into the project structure a little more.

**Comment by mix3d** [comment] 2021-06-15 18:59
Dupe of #8 , so if you create a PR I'm sure people will be happy :)

**Comment by hotfistdotcom** [comment] 2022-02-23 16:16
Would also strong like this.

**Comment by uwburn** [comment] 2022-08-03 06:29
Duplicate of #8

**Closed as completed by uwburn** 2022-08-03 06:29 UTC
Labels: duplicate
