### ISSUE TITLE
How is the Bt Smart branch going?

### ISSUE THREAD

**Issue by Funkiekitty** [uwburn/cardia#5] opened 2016-12-13 10:28 UTC
Hello! 
I was wondering how it was possessing, I've been looking for hours but you seem to be the only one with this solution! 
I just got my monitor today and I tryed to dl you're pre-lease but it won't open. 
Hope you're doing well.

**Comment by uwburn** [comment] 2017-06-20 20:15
This is duplicate of #3, please refer to it.

**Closed as completed by uwburn** 2017-06-20 20:15 UTC
Labels: duplicate

**Comment by uwburn** [comment] 2017-06-24 21:15
Please checkout #3 for updated version, discussion there.
